"use client";
import { normaliseAllocationDefaults } from "../../lib/financial-learning-engine";
import type { AllocationBlock, FinancialBlockResponse } from "../../lib/financial-learning-engine-types";
import LearningBlockShell from "./LearningBlockShell";
export default function AllocationLearningBlock({ block, response, onChange }: { block: AllocationBlock; response?: FinancialBlockResponse; onChange: (r: FinancialBlockResponse) => void }) {
  const values = (response?.value && typeof response.value === "object" ? response.value : normaliseAllocationDefaults(block)) as Record<string, number>;
  const allocated = Object.values(values).reduce((sum, value) => sum + Number(value || 0), 0);
  const remaining = block.total - allocated;
  const update = (id: string, next: number) => onChange({ blockId: block.id, blockType: block.type, value: { ...values, [id]: next }, answeredAt: new Date().toISOString() });
  return <LearningBlockShell eyebrow={block.eyebrow ?? "Allocate"} title={block.title}><h4 style={{ margin: 0, fontFamily: 'Georgia, "Times New Roman", serif', fontSize: "27px", fontWeight: 500 }}>{block.prompt}</h4><div style={{ marginTop: "13px", display: "flex", justifyContent: "space-between", color: remaining < 0 ? "#ffabab" : "#9af3c3", fontSize: "11px", fontWeight: 800 }}><span>Total: {block.total.toLocaleString("en-SG")} {block.unit ?? ""}</span><span>Remaining: {remaining.toLocaleString("en-SG")} {block.unit ?? ""}</span></div><div style={{ marginTop: "15px", display: "grid", gap: "10px" }}>{block.buckets.map((bucket) => { const current = Number(values[bucket.id] ?? 0); return <div key={bucket.id} style={{ borderRadius: "14px", border: "1px solid rgba(255,255,255,0.07)", background: "rgba(255,255,255,0.025)", padding: "12px" }}><div style={{ display: "flex", justifyContent: "space-between", gap: "10px" }}><div><strong style={{ fontSize: "12px" }}>{bucket.label}</strong>{bucket.description && <div style={{ marginTop: "3px", color: "rgba(255,255,255,0.38)", fontSize: "9px" }}>{bucket.description}</div>}</div><strong style={{ color: "#8ee8ff" }}>{current.toLocaleString("en-SG")}</strong></div><input type="range" min={bucket.min ?? 0} max={bucket.max ?? block.total} step={1} value={current} onChange={(e: any) => update(bucket.id, Number(e.target.value))} style={{ width: "100%", marginTop: "9px", accentColor: "#58d8ff" }} /></div>; })}</div>{remaining === 0 && block.completionMessage && <div style={{ marginTop: "13px", color: "#9af3c3", fontSize: "11px" }}>{block.completionMessage}</div>}</LearningBlockShell>;
}
