import type { MoneyLabLesson } from "./money-lab-types";

export const MONEY_LAB_LESSONS: MoneyLabLesson[] = [
  {
    key: "saving-basics",
    order: 1,
    icon: "◎",
    title: "What is saving?",
    shortTitle: "Saving",
    description: "Learn why setting DT aside can make a future goal easier to reach.",
    duration: "1–2 min",
    rewardDt: 5,
    concepts: ["Goals", "Set aside", "Patience"],
    steps: [
      {
        type: "info",
        eyebrow: "Financial Foundations · Saving",
        title: "Saving means choosing later over now.",
        body: "When you save, you keep some of your Dream Tokens instead of spending all of them today. Those DT stay ready for something you care about later.",
        example: "You have 800 DT and set 200 DT aside for a rover upgrade. You still own all 800 DT, but 200 DT now has a job.",
      },
      {
        type: "info",
        eyebrow: "A simple plan",
        title: "Give your savings a clear goal.",
        body: "A target makes saving easier to follow. Decide what you want, how much it costs, and how much you can set aside each time you earn DT.",
        example: "Goal: 1,000 DT. Saved: 400 DT. Remaining: 600 DT.",
      },
      {
        type: "quiz",
        question: "Milo earns 300 DT and moves 100 DT into a savings goal. What happened?",
        options: [
          "He lost 100 DT",
          "He still owns it, but set it aside",
          "The Bank doubled it",
          "He spent it",
        ],
        correctIndex: 1,
        explanation: "Correct. Savings DT still belong to Milo. They are simply reserved for the goal instead of being available to spend immediately.",
      },
      {
        type: "quiz",
        question: "Which is the clearest savings goal?",
        options: ["Save some DT", "Never spend anything", "Save 1,500 DT for a rover upgrade", "Get rich"],
        correctIndex: 2,
        explanation: "A useful goal says what you are saving for and gives you a target amount to work towards.",
      },
    ],
  },
  {
    key: "interest-basics",
    order: 2,
    icon: "%",
    title: "What is interest?",
    shortTitle: "Interest",
    description: "See how interest can add an extra amount to money over time.",
    duration: "1–2 min",
    rewardDt: 5,
    concepts: ["Principal", "Interest", "Return"],
    steps: [
      {
        type: "info",
        eyebrow: "Financial Foundations · Interest",
        title: "Interest is an extra amount.",
        body: "The amount you start with is called the principal. Interest is the extra amount added according to an agreed rate or rule.",
        example: "Principal: 1,000 DT. Interest: 40 DT. Final amount: 1,040 DT.",
      },
      {
        type: "info",
        eyebrow: "Read the whole number",
        title: "A percentage tells you the rate.",
        body: "A 4% return means 4 DT for every 100 DT of principal. In Dreamscape, Bank Bond returns are fixed game-economy amounts shown before you confirm.",
        example: "4% of 500 DT = 20 DT, so the final amount is 520 DT.",
      },
      {
        type: "quiz",
        question: "A Dreamscape Bond starts with 1,000 DT and earns 40 DT. Which amount is the interest?",
        options: ["1,000 DT", "40 DT", "1,040 DT", "4,000 DT"],
        correctIndex: 1,
        explanation: "The 1,000 DT is the principal. The extra 40 DT is the interest, making 1,040 DT altogether.",
      },
      {
        type: "quiz",
        question: "If 500 DT earns a fixed 4% return in this game example, what is the interest?",
        options: ["4 DT", "20 DT", "40 DT", "504 DT"],
        correctIndex: 1,
        explanation: "4% of 500 DT is 20 DT. Add that to the 500 DT principal for a final amount of 520 DT.",
      },
    ],
  },
  {
    key: "bond-basics",
    order: 3,
    icon: "◆",
    title: "What is a bond?",
    shortTitle: "Bonds",
    description: "Learn principal, maturity and fixed return through Dreamscape Bank Bonds.",
    duration: "1–2 min",
    rewardDt: 5,
    concepts: ["Term", "Maturity", "Fixed return"],
    steps: [
      {
        type: "info",
        eyebrow: "Financial Foundations · Bonds",
        title: "A bond has a term and a maturity date.",
        body: "In Milo’s Bank, you choose a Dreamscape Bond and lock eligible earned DT for a fixed period. While it is locked, that principal cannot be spent elsewhere.",
        example: "A 7-day Bond bought today reaches maturity seven days later.",
      },
      {
        type: "info",
        eyebrow: "At maturity",
        title: "The principal unlocks and the return can be collected.",
        body: "The original principal was never spent; it was reserved. When the Bond matures and is collected, the principal becomes available again and the fixed game return is credited.",
        example: "1,000 DT principal + 40 DT interest = 1,040 DT after collection.",
      },
      {
        type: "quiz",
        question: "What does a Bond’s maturity date tell you?",
        options: ["When the Bond term ends", "When you bought your first DT", "When all DT disappear", "When the market opens"],
        correctIndex: 0,
        explanation: "Maturity is the end of the Bond’s agreed term. That is when the matured Bond can be collected.",
      },
      {
        type: "quiz",
        question: "While 1,000 DT is locked in an active Milo’s Bank Bond, can those same 1,000 DT also be spent on a rover?",
        options: ["Yes, twice", "Only half", "No, they are reserved", "Only on weekends"],
        correctIndex: 2,
        explanation: "No. Locked principal is still yours, but it is reserved until the Bond is settled.",
      },
    ],
  },
  {
    key: "saving-vs-investing",
    order: 4,
    icon: "↗",
    title: "Saving vs investing",
    shortTitle: "Save or invest?",
    description: "Understand why saving and investing can have different jobs.",
    duration: "1–2 min",
    rewardDt: 5,
    concepts: ["Purpose", "Time", "Uncertainty"],
    steps: [
      {
        type: "info",
        eyebrow: "Financial Foundations · Choices",
        title: "Saving and investing are not the same thing.",
        body: "Saving usually focuses on keeping money available for a goal or future need. Investing means putting money into something that may change in value or produce a return.",
        example: "Saving for a near-term rover upgrade is a different job from buying a changing-value asset in Milo’s Exchange.",
      },
      {
        type: "info",
        eyebrow: "Match the tool to the job",
        title: "Time and uncertainty matter.",
        body: "A short-term goal often needs money to be predictable and accessible. Longer-term investing may involve more uncertainty. Dreamscape lets you practise both ideas with fictional DT.",
        example: "Need the DT soon? A savings goal keeps the target clear. Exploring changing values? The Exchange teaches a different concept.",
      },
      {
        type: "quiz",
        question: "You want a 2,000 DT upgrade very soon and do not want the amount to change. Which idea best matches that goal?",
        options: ["Saving towards the target", "Choosing the most uncertain asset", "Spending everything now", "Ignoring the price"],
        correctIndex: 0,
        explanation: "Saving fits a clear near-term target because the focus is on setting aside the amount you expect to need.",
      },
      {
        type: "quiz",
        question: "Which statement is most accurate?",
        options: ["Saving and investing are identical", "Investing always makes money", "Different money tools can serve different goals", "Saving guarantees you become rich"],
        correctIndex: 2,
        explanation: "Different tools serve different purposes. There is no single choice that fits every goal or time horizon.",
      },
    ],
  },
  {
    key: "risk-and-return",
    order: 5,
    icon: "△",
    title: "Risk and return",
    shortTitle: "Risk & return",
    description: "Learn why a possible higher return can come with more uncertainty.",
    duration: "1–2 min",
    rewardDt: 5,
    concepts: ["Risk", "Return", "Uncertainty"],
    steps: [
      {
        type: "info",
        eyebrow: "Financial Foundations · Risk",
        title: "Return is what you gain. Risk is uncertainty about what happens.",
        body: "Some choices have predictable outcomes. Others can rise or fall. When the outcome is less certain, you should understand what could happen before committing resources.",
        example: "Milo’s Exchange prices can change. A Dreamscape Bank Bond instead shows its fixed game return before purchase.",
      },
      {
        type: "info",
        eyebrow: "Important real-world idea",
        title: "A bigger possible return is not a promise.",
        body: "In real-world investing, higher possible returns often come with greater risk of losing value. Returns are not guaranteed just because an opportunity looks exciting.",
        example: "Always separate a possible outcome from a guaranteed outcome.",
      },
      {
        type: "quiz",
        question: "An asset can rise a lot, but it can also fall a lot. What does that tell you?",
        options: ["There is uncertainty and risk", "Profit is guaranteed", "It is the same as cash", "Price cannot change"],
        correctIndex: 0,
        explanation: "A wider range of possible outcomes means more uncertainty. That uncertainty is part of risk.",
      },
      {
        type: "quiz",
        question: "Which sentence is safest to remember about real-world investing?",
        options: ["Higher possible return always means guaranteed profit", "Past gains guarantee future gains", "Possible return and guaranteed return are different", "Risk disappears if many people buy"],
        correctIndex: 2,
        explanation: "Possible return is not a promise. Real-world investments can gain or lose value.",
      },
    ],
  },
  {
    key: "needs-vs-wants",
    order: 6,
    icon: "◇",
    title: "Needs vs wants",
    shortTitle: "Needs & wants",
    description: "Practise deciding what matters first when resources are limited.",
    duration: "1–2 min",
    rewardDt: 5,
    concepts: ["Priority", "Choice", "Budget"],
    steps: [
      {
        type: "info",
        eyebrow: "Financial Foundations · Priorities",
        title: "A need and a want can both matter—but not in the same way.",
        body: "A need is something important for basic living or an essential purpose. A want is something you would like but can usually delay or choose not to buy.",
        example: "In everyday life, food needed for a meal is different from buying an extra collectible simply because you like it.",
      },
      {
        type: "info",
        eyebrow: "When DT is limited",
        title: "Priorities help you decide what comes first.",
        body: "A simple budget means deciding how limited resources will be used. You can set aside some, spend some, and leave room for future goals instead of treating every choice as equally urgent.",
        example: "If you have 1,000 DT, you might reserve part for a planned upgrade before buying optional decorations.",
      },
      {
        type: "quiz",
        question: "You are saving for a required rover repair but also want a new decorative item. DT is limited. What idea helps most?",
        options: ["Prioritise the more important purpose first", "Buy both even without enough DT", "Ignore the repair", "Spend randomly"],
        correctIndex: 0,
        explanation: "When resources are limited, ranking priorities helps you protect the more important goal before optional spending.",
      },
      {
        type: "quiz",
        question: "What is a budget mainly for?",
        options: ["Making every purchase free", "Planning how limited resources will be used", "Stopping all spending forever", "Guaranteeing investment returns"],
        correctIndex: 1,
        explanation: "A budget is a plan for how available resources will be allocated among different purposes.",
      },
    ],
  },
];

export const MONEY_LAB_TOTAL_REWARD = MONEY_LAB_LESSONS.reduce(
  (sum, lesson) => sum + lesson.rewardDt,
  0,
);
